(function(root){
'use strict';
class GameAudio{
 constructor(){this.ctx=null;this.master=null;this.enabled=true;this.volume=.55;this.voiceEnabled=true;this.current=null;this.lastVoice=-Infinity;this.lastFX={};this.seen=new Set();this.onCaption=()=>{};this.status=()=>{};this.audioCache=new Map();}
 unlock(){try{if(!this.ctx){const C=root.AudioContext||root.webkitAudioContext;if(C){this.ctx=new C();this.master=this.ctx.createGain();this.master.gain.value=this.enabled?this.volume:0;this.master.connect(this.ctx.destination)}}if(this.ctx?.state==='suspended')this.ctx.resume().catch(()=>{});}catch{} }
 setVolume(value){this.volume=Math.max(0,Math.min(1,Number(value)));if(this.master)this.master.gain.value=this.enabled?this.volume:0;if(this.current)this.current.volume=this.volume;}
 mute(value){this.enabled=!value;if(this.master)this.master.gain.value=this.enabled?this.volume:0;if(!this.enabled)this.stopVoice();}
 stopVoice(){if(this.current){this.current.pause();this.current=null}root.speechSynthesis?.cancel();}
 tone(freq,duration,type='sine',gain=.1,slide=0){if(!this.ctx||!this.enabled)return;const t=this.ctx.currentTime,osc=this.ctx.createOscillator(),env=this.ctx.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,t);if(slide)osc.frequency.exponentialRampToValueAtTime(Math.max(25,slide),t+duration);env.gain.setValueAtTime(.0001,t);env.gain.exponentialRampToValueAtTime(gain,t+.007);env.gain.exponentialRampToValueAtTime(.0001,t+duration);osc.connect(env);env.connect(this.master);osc.start(t);osc.stop(t+duration+.02);osc.onended=()=>{osc.disconnect();env.disconnect()};}
 noise(duration,gain=.12,frequency=1600){if(!this.ctx||!this.enabled)return;const len=Math.ceil(duration*this.ctx.sampleRate),buffer=this.ctx.createBuffer(1,len,this.ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<len;i++)data[i]=(Math.random()*2-1)*Math.exp(-i/len*6);const src=this.ctx.createBufferSource(),filter=this.ctx.createBiquadFilter(),env=this.ctx.createGain();src.buffer=buffer;filter.type='lowpass';filter.frequency.value=frequency;env.gain.value=gain;src.connect(filter);filter.connect(env);env.connect(this.master);src.start();src.onended=()=>{src.disconnect();filter.disconnect();env.disconnect()};}
 fx(kind,modern=false){if(!this.enabled)return;const now=Date.now();if(now-(this.lastFX[kind]||0)<(kind==='combat'?160:kind==='gather'||kind==='build'?350:80))return;this.lastFX[kind]=now;switch(kind){case'select':this.tone(620,.045,'sine',.045);break;case'order':this.tone(440,.08,'triangle',.06,720);break;case'build':this.noise(.13,.12,1400);this.tone(210,.12,'triangle',.07,80);break;case'gather':this.noise(.07,.065,2400);break;case'combat':if(modern){this.noise(.2,.18,4200);this.tone(90,.2,'sawtooth',.045,35)}else{this.noise(.08,.10,6000);this.tone(850,.11,'triangle',.055,350)}break;case'ready':this.tone(660,.15,'sine',.09);setTimeout(()=>this.tone(880,.2,'sine',.07),100);break;case'error':this.tone(160,.18,'triangle',.07,100);break;case'alarm':[0,220,440].forEach(d=>setTimeout(()=>{this.tone(880,.12,'square',.05);this.tone(660,.12,'square',.05)},d));break;case'victory':[440,554,660,880].forEach((f,i)=>setTimeout(()=>this.tone(f,.5,'triangle',.10),i*170));break;case'defeat':this.tone(220,.8,'triangle',.08,80);break;case'research':this.tone(523,.12,'sine',.07);setTimeout(()=>this.tone(784,.18,'sine',.07),120);break;case'ageup':[523,659,784,1047].forEach((f,i)=>setTimeout(()=>this.tone(f,.35,'triangle',.09),i*140));break;case'wonder':[392,523,659,784,1047].forEach((f,i)=>setTimeout(()=>{this.tone(f,.6,'triangle',.09);this.tone(f/2,.6,'sine',.05)},i*160));break;case'emp':this.tone(1800,.35,'sawtooth',.05,120);this.noise(.3,.12,3000);setTimeout(()=>this.tone(90,.4,'square',.05,30),120);break;case'hazard':this.tone(330,.3,'triangle',.07,220);setTimeout(()=>this.tone(262,.4,'triangle',.07,180),260);break;case'built':this.tone(392,.1,'triangle',.06);setTimeout(()=>this.tone(523,.16,'triangle',.06),90);break;case'destroyed':this.noise(.4,.16,900);this.tone(110,.5,'sawtooth',.06,40);break;case'lost':this.tone(196,.25,'triangle',.05,150);break;case'launch':this.noise(.5,.1,2200);this.tone(140,.5,'sawtooth',.05,420);break;case'blast':this.noise(.6,.2,700);this.tone(60,.6,'square',.07,25);break;case'intercept':this.tone(1200,.12,'square',.05,600);this.noise(.15,.08,3000);break;case'diplomacy':this.tone(587,.14,'sine',.07);setTimeout(()=>this.tone(440,.22,'sine',.07),140);break;case'landmark':[523,659].forEach((f,i)=>setTimeout(()=>this.tone(f,.2,'triangle',.08),i*110));break;case'eliminated':[330,262,196].forEach((f,i)=>setTimeout(()=>this.tone(f,.3,'triangle',.08),i*150));break;case'bell':[0,180,360].forEach(d=>setTimeout(()=>{this.tone(988,.35,'triangle',.07);this.tone(1319,.25,'sine',.03)},d));break;case'depleted':this.tone(294,.2,'triangle',.06,240);break;case'popblock':this.tone(247,.15,'square',.05);setTimeout(()=>this.tone(247,.15,'square',.05),200);break;case'objective':[659,784,988].forEach((f,i)=>setTimeout(()=>this.tone(f,.25,'triangle',.08),i*120));break;}}
 say(nation,action='select',force=false){const c=root.CULTURES?.[nation];if(!c)return;const line=c.lines[action]||c.lines.select;const now=Date.now();if(!force&&now-this.lastVoice<600)return;this.lastVoice=now;this.onCaption(line,c.lang,action);if(!this.enabled||!this.voiceEnabled)return;this.stopVoice();const src='voices/'+c.code+'-'+action+'.mp3';let a=this.audioCache.get(src);if(!a){a=new Audio(src);a.preload='auto';this.audioCache.set(src,a)}this.current=a;a.currentTime=0;a.volume=this.volume;a.onerror=()=>{if(this.current!==a||!this.enabled||!this.voiceEnabled)return;this.status('人物語音載入失敗：'+c.name);this.fallback(c,line)};const play=a.play();if(play?.catch)play.catch(err=>{if(err.name!=='AbortError')this.status('請按「試聽」啟用人物語音。')});}
 fallback(c,line){if(!root.speechSynthesis||!root.SpeechSynthesisUtterance)return;const voice=root.speechSynthesis.getVoices().find(v=>v.lang.toLowerCase()===c.lang.toLowerCase());if(!voice)return;const u=new SpeechSynthesisUtterance(line);u.voice=voice;u.lang=c.lang;u.volume=this.volume;root.speechSynthesis.speak(u)}
 update(game,isVisible){for(const u of game.units){if(u.strike==null||u.strike<0||game.time-u.strike>.3||u.hp<=0||!isVisible(u))continue;const key=u.id+':'+u.strike;if(!this.seen.has(key)){this.seen.add(key);this.fx('combat',game.mode==='modern')}}if(this.seen.size>600)this.seen.clear();if(Math.floor(game.time*2)%2===0){const worker=game.units.find(u=>u.owner===0&&u.hp>0&&u.type===0&&u.work>0&&!u.path.length&&u.phase!=='return'&&isVisible(u)&&['gather','build'].includes(u.task.kind));if(worker)this.fx(worker.task.kind==='build'?'build':'gather')}}
}
root.GameAudio=GameAudio;if(typeof module!=='undefined')module.exports={GameAudio};
})(typeof window!=='undefined'?window:globalThis);
