'use strict';
const $=id=>document.getElementById(id);
const MODES={
 classic:{name:'古代中世紀',ages:['村落時代','封建時代','城堡時代'],resources:['糧食','木材','黃金'],buildings:['農田','伐木場','市集'],units:['步兵','弓兵','騎兵'],power:[1,1.5,2.6],cost:[[35,0,10],[30,30,15],[70,0,45]],speed:1},
 modern:{name:'現代軍事',ages:['工業時代','機械化時代','資訊時代'],resources:['補給','鋼材','能源'],buildings:['補給站','鋼鐵廠','煉油廠'],units:['步兵','裝甲車','主戰坦克'],power:[1,2.1,4],cost:[[40,0,10],[30,55,25],[70,90,65]],speed:1.5},
 fantasy:{name:'架空歷史',ages:['黎明時代','符文時代','巨龍時代'],resources:['糧食','靈木','魔晶'],buildings:['豐饒農莊','靈木林','魔晶礦'],units:['守衛','符文法師','龍騎士'],power:[1.2,2.5,4.8],cost:[[40,0,10],[35,25,40],[65,40,95]],speed:1.2}
};
const PLACES=[
 ['tw','台灣','台北',121.56,25.03],['cn','中國大陸','北京',116.4,39.9],['jp','日本','東京',139.69,35.68],['kr','韓國','首爾',126.98,37.56],['mn','蒙古','烏蘭巴托',106.9,47.9],['vn','越南','河內',105.83,21.03],['ph','菲律賓','馬尼拉',120.98,14.6],['th','泰國','曼谷',100.5,13.75],['in','印度','德里',77.2,28.6],['ru','俄羅斯','莫斯科',37.62,55.75],['gb','英國','倫敦',-.12,51.5],['fr','法國','巴黎',2.35,48.85],['de','德國','柏林',13.4,52.52],['eg','埃及','開羅',31.24,30.04],['us','美國','華盛頓',-77.04,38.9],['br','巴西','巴西利亞',-47.88,-15.8],['au','澳洲','坎培拉',149.13,-35.28]
];
let state=null,selected='tw',sending=null,paused=false,speed=1,cam={lon:121,lat:32,scale:13},logs=[],last=0,noticeTimer;
const canvas=$('map'),ctx=canvas.getContext('2d');let width=800,height=700;
function notify(t){$('notice').textContent=t;$('notice').classList.add('visible');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('notice').classList.remove('visible'),3200)}
function log(t){logs.unshift(t);logs=logs.slice(0,7);$('log').replaceChildren(...logs.map(t=>{const li=document.createElement('li');li.textContent=t;return li}))}
function mode(){return MODES[state?.mode||$('mode').value]}
function city(id){return state.cities.find(c=>c.id===id)}
function count(c){return c.units.reduce((a,b)=>a+b,0)}
function strength(units,age){return units.reduce((a,n,i)=>a+n*mode().power[i],0)*(1+age*.3)}
function available(){return PLACES.filter((p,i)=>$('scenario').value==='world'||i<8)}
function factions(){const prev=$('faction').value;$('faction').replaceChildren(...available().map(p=>new Option(p[1]+' · '+p[2],p[0])));if(available().some(p=>p[0]===prev))$('faction').value=prev}
function begin(){const faction=$('faction').value,scenario=$('scenario').value;state={mode:$('mode').value,scenario,difficulty:$('difficulty').value,time:0,age:0,res:[300,250,200],armies:[],ai:0,over:false,home:faction,cities:available().map(p=>({id:p[0],nation:p[1],name:p[2],lon:p[3],lat:p[4],owner:'neutral',capital:false,units:[8,0,0],hp:180,maxHp:180,buildings:[0,0,0],queue:[]}))};
 const own=city(faction);Object.assign(own,{owner:'player',capital:true,units:[18,6,0],hp:320,maxHp:320,buildings:[1,1,1]});
 const opponents=state.cities.filter(c=>c!==own).sort((a,b)=>Math.hypot(a.lon-own.lon,a.lat-own.lat)-Math.hypot(b.lon-own.lon,b.lat-own.lat));
 for(const c of opponents.slice(0,scenario==='asia'?2:3))Object.assign(c,{owner:'enemy',capital:true,units:[14,4,0],hp:260,maxHp:260,buildings:[1,1,1]});
 selected=faction;sending=null;paused=false;speed=1;logs=[];focusHome();$('setup').close();$('result').close();$('cancelSetup').hidden=false;$('pause').textContent='Ⅱ 暫停';$('speed').textContent='1×';$('theatre').textContent=scenario==='asia'?'東亞戰場':'世界遠征';$('campaign').textContent=mode().name+' / '+own.nation;$('objective').textContent='守住首都，征服所有敵方首都。';log('戰役開始。先擴建經濟，再招募軍隊。');render();}
function income(){return [0,1,2].map(i=>state.cities.filter(c=>c.owner==='player').reduce((s,c)=>s+1+c.buildings[i]*2,0))}
function afford(cost){return cost.every((v,i)=>state.res[i]>=v)}
function pay(cost){if(!afford(cost)){notify('資源不足，請等待生產或擴建設施。');return false}cost.forEach((v,i)=>state.res[i]-=v);return true}
function allowed(){return state&&!state.over&&!paused&&!$('setup').open&&!$('helpDialog').open}
function build(i){const c=city(selected);if(!allowed()||c.owner!=='player')return;const n=c.buildings[i];if(n>=5){notify('此設施已達上限。');return}if(pay([20,60+n*30,20+n*10])){c.buildings[i]++;log(c.name+'建成'+mode().buildings[i]+'，產量提升。');render()}}
function recruit(i){const c=city(selected);if(!allowed()||c.owner!=='player')return;if(i>state.age){notify('請先升級時代。');return}if(c.queue.length>=5){notify('招募佇列已滿。');return}const cost=mode().cost[i].map(n=>n*5);if(pay(cost)){c.queue.push({i,remaining:5+i*3});render()}}
function upgrade(){if(!allowed()||state.age>=2)return;const n=state.age+1;if(pay([300*n,200*n,200*n])){state.age++;log('文明進入'+mode().ages[state.age]+'！所有軍隊戰力提升。');render()}}
function dispatch(from,to,ratio=1,owner='player'){if(from.id===to.id)return false;const units=from.units.map(n=>Math.floor(n*ratio));if(units.reduce((a,b)=>a+b,0)===0){notify('沒有可派遣的部隊。');return false}from.units=from.units.map((n,i)=>n-units[i]);let dx=to.lon-from.lon;if(dx>180)dx-=360;if(dx< -180)dx+=360;const distance=Math.hypot(dx*Math.cos(from.lat*Math.PI/180),to.lat-from.lat);const total=Math.max(8,Math.min(100,distance*.85/mode().speed));state.armies.push({from:from.id,to:to.id,owner,units,age:owner==='player'?state.age:Math.min(2,Math.floor(state.time/180)),progress:0,total,dx});if(owner==='player')log(from.name+'派出 '+units.reduce((a,b)=>a+b,0)+' 人前往'+to.name+'。');return true}
function choose(id){if(!state)return;if(sending){const from=city(sending.id),to=city(id);if(id===from.id){sending=null;notify('已取消派遣。')}else if(allowed()&&dispatch(from,to,sending.ratio)){sending=null;notify('部隊已出發，抵達後自動交戰。')}}selected=id;render()}
function arrive(a){const target=city(a.to);if(target.owner===a.owner){target.units=target.units.map((n,i)=>n+a.units[i]);return}const attack=strength(a.units,a.age),defAge=target.owner==='player'?state.age:Math.min(2,Math.floor(state.time/180));const unitDefense=strength(target.units,defAge),defense=unitDefense+target.hp/12;
 if(attack>defense){const previous=target.owner;target.owner=a.owner;target.units=a.units.map(n=>Math.max(0,Math.ceil(n*(1-defense/attack)*.85)));target.hp=target.maxHp*.55;target.queue=[];log((a.owner==='player'?'我軍':'敵軍')+'攻占'+target.name+'！');if(target.id===state.home&&previous==='player')end(false)}else{const remaining=Math.max(0,1-attack/defense);target.units=target.units.map(n=>Math.floor(n*remaining));target.hp=Math.max(15,target.hp*(.4+.6*remaining));log((a.owner==='player'?'我軍攻打':'敵軍進攻')+target.name+'未能突破防線。')}
 if(!state.over&&!state.cities.some(c=>c.capital&&c.owner==='enemy'))end(true);
}
function end(win){state.over=true;sending=null;$('resultTitle').textContent=win?'你的旗幟，迎風而立。':'首都淪陷，戰役結束。';$('resultText').textContent=(win?'你已攻下所有敵方首都。':'重新布局經濟與守軍，再次出征。')+' 戰役時間 '+formatTime(state.time)+'。';$('result').showModal()}
function tick(dt){if(!allowed())return;state.time+=dt;const inc=income();state.res=state.res.map((n,i)=>n+inc[i]*dt);for(const c of state.cities){if(c.owner==='neutral')continue;c.hp=Math.min(c.maxHp,c.hp+dt*.7);if(c.queue.length){c.queue[0].remaining-=dt;if(c.queue[0].remaining<=0){const q=c.queue.shift();c.units[q.i]+=5;if(c.owner==='player')log(c.name+'的 5 名'+mode().units[q.i]+'已就緒。')}}}
 const arrived=[];for(const a of state.armies){a.progress+=dt/a.total;if(a.progress>=1)arrived.push(a)}state.armies=state.armies.filter(a=>a.progress<1);for(const a of arrived){if(!state.over)arrive(a)}
 state.ai+=dt;const period={easy:24,normal:16,hard:10}[state.difficulty];if(state.ai>=period){state.ai=0;for(const c of state.cities.filter(c=>c.owner==='enemy')){c.units[0]+=4;c.units[Math.min(2,Math.floor(state.time/180))]+=2;const targets=state.cities.filter(t=>t.owner==='player').sort((a,b)=>Math.hypot(a.lon-c.lon,a.lat-c.lat)-Math.hypot(b.lon-c.lon,b.lat-c.lat));if(state.time>50&&count(c)>23&&targets.length){dispatch(c,targets[0],.6,'enemy');log(c.name+'的敵軍正向'+targets[0].name+'行軍。')}}} }
function formatTime(t){return Math.floor(t/60).toString().padStart(2,'0')+':'+Math.floor(t%60).toString().padStart(2,'0')}
function costText(cost){return cost.map((n,i)=>n?mode().resources[i]+' '+n:'').filter(Boolean).join(' · ')}
function action(title,sub,right,handler,disabled=false){const b=document.createElement('button');b.className='action';const l=document.createElement('span');l.textContent=title;const s=document.createElement('small');s.textContent=sub;l.append(s);const r=document.createElement('strong');r.textContent=right;b.append(l,r);b.disabled=disabled;b.onclick=handler;return b}
function section(title,items){const h=document.createElement('h3');h.textContent=title;const div=document.createElement('div');div.className='actions';div.append(...items);$('commands').append(h,div)}
function render(){if(!state)return;const m=mode(),inc=income();$('resources').innerHTML=m.resources.map((r,i)=>'<div class="resource"><span>'+r+'</span><b>'+Math.floor(state.res[i])+'</b><small>+'+inc[i]+'/秒</small></div>').join('')+'<div class="resource"><span>軍力</span><b>'+state.cities.filter(c=>c.owner==='player').reduce((a,c)=>a+count(c),state.armies.filter(a=>a.owner==='player').reduce((s,a)=>s+a.units.reduce((x,y)=>x+y,0),0))+'</b><small>'+m.ages[state.age]+'</small></div>';$('clock').textContent=formatTime(state.time);
 const c=city(selected);$('cityName').textContent=(c.capital?'★ ':'')+c.name;$('citySelect').replaceChildren(...state.cities.map(c=>new Option((c.owner==='player'?'◆ ':c.owner==='enemy'?'敵 · ':'◇ ')+c.nation+' / '+c.name,c.id)));$('citySelect').value=selected;$('cityInfo').innerHTML='<div class="info-line"><span>'+({player:'我方領地',enemy:'敵方領地',neutral:'中立領地'}[c.owner])+'</span><span>'+c.nation+'</span></div><div class="info-line"><span>城防</span><span>'+Math.ceil(c.hp)+' / '+c.maxHp+'</span></div><div class="bar"><i style="width:'+c.hp/c.maxHp*100+'%"></i></div><div class="info-line"><span>駐軍</span><span>'+count(c)+' 人</span></div><p class="hint">'+c.units.map((n,i)=>m.units[i]+' '+n).join(' ／ ')+'</p>';$('commands').replaceChildren();
 if(c.owner==='player'){section('建設 / 持續生產',m.buildings.map((b,i)=>action(b,costText([20,60+c.buildings[i]*30,20+c.buildings[i]*10]),c.buildings[i]+'/5',()=>build(i),c.buildings[i]>=5||!afford([20,60+c.buildings[i]*30,20+c.buildings[i]*10]))));section('招募 / 每批 5 人',m.units.map((u,i)=>action(u,i>state.age?'於'+m.ages[i]+'解鎖':costText(m.cost[i].map(n=>n*5)),i>state.age?'鎖定':'＋5',()=>recruit(i),i>state.age||c.queue.length>=5||!afford(m.cost[i].map(n=>n*5)))));if(c.queue.length){const p=document.createElement('p');p.className='hint';p.textContent='招募中：'+c.queue.map(q=>m.units[q.i]+' '+Math.ceil(q.remaining)+'秒').join(' → ');$('commands').append(p)}
 section('軍事指令',[action(sending?'取消派遣':'派遣軍隊','點選按鈕後，再選擇目標城市','→',()=>{if(!allowed())return;sending=sending?null:{id:c.id,ratio:Number($('ratio').value)};notify(sending?'請點選目標城市，或用領地選單指定。':'已取消派遣。');render()},count(c)===0)]);const row=document.createElement('div');row.className='send-row';const label=document.createElement('label');label.textContent='出征比例';label.style.margin='0';const select=document.createElement('select');select.id='ratio';select.setAttribute('aria-label','出征比例');select.append(new Option('全部兵力','1'),new Option('保留一半守軍','0.5'));if(sending)select.value=String(sending.ratio);label.append(select);row.append(label);$('commands').append(row);
 if(state.age<2)section('文明發展',[action('升級至'+m.ages[state.age+1],costText([300*(state.age+1),200*(state.age+1),200*(state.age+1)]),'↑',upgrade,!afford([300*(state.age+1),200*(state.age+1),200*(state.age+1)]))]);
 }else{const p=document.createElement('p');p.className='hint';p.textContent='選擇我方城市，按「派遣軍隊」，再選擇這座城市即可發動進攻。城防與駐軍共同決定防禦力。';$('commands').append(p)}
}
function project(lon,lat){return [(lon-cam.lon)*cam.scale+width/2,(cam.lat-lat)*cam.scale+height/2]}
function resize(){const rect=canvas.getBoundingClientRect();width=rect.width;height=rect.height;const dpr=Math.min(2,window.devicePixelRatio||1);canvas.width=width*dpr;canvas.height=height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}
function focusHome(){const c=state?city(state.home):{lon:121,lat:32};cam={lon:c.lon,lat:c.lat,scale:Math.max(7,Math.min(width/47,height/42))}}
function draw(){ctx.clearRect(0,0,width,height);ctx.fillStyle='#0b202c';ctx.fillRect(0,0,width,height);ctx.lineWidth=1;ctx.strokeStyle='#1b3541';for(let lon=-180;lon<=180;lon+=10){const x=project(lon,0)[0];ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,height);ctx.stroke()}for(let lat=-80;lat<=80;lat+=10){const y=project(0,lat)[1];ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(width,y);ctx.stroke()}
 for(const f of window.WORLD){const polys=f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates;ctx.beginPath();for(const poly of polys)for(const ring of poly){ring.forEach(([lon,lat],i)=>{const [x,y]=project(lon,lat);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath()}ctx.fillStyle='#243e43';ctx.fill('evenodd');ctx.strokeStyle='#476064';ctx.lineWidth=.7;ctx.stroke()}
 ctx.fillStyle='#66878f';ctx.font='italic 16px Georgia';const sea=project(137,23);ctx.fillText('PACIFIC OCEAN',sea[0],sea[1]);if(!state)return;
 for(const a of state.armies){const from=city(a.from),to=city(a.to),p=project(from.lon,from.lat),q=project(from.lon+a.dx,to.lat);ctx.beginPath();ctx.setLineDash([4,6]);ctx.moveTo(...p);ctx.lineTo(...q);ctx.strokeStyle=a.owner==='player'?'#69c4cf88':'#ef898288';ctx.stroke();ctx.setLineDash([]);const x=p[0]+(q[0]-p[0])*a.progress,y=p[1]+(q[1]-p[1])*a.progress;ctx.fillStyle=a.owner==='player'?'#9be7ec':'#ffaba2';ctx.beginPath();ctx.arc(x,y,5,0,Math.PI*2);ctx.fill();ctx.font='12px system-ui';ctx.fillText(a.units.reduce((x,y)=>x+y,0),x+8,y-7)}
 for(const c of state.cities){const [x,y]=project(c.lon,c.lat);if(x< -80||x>width+80||y< -40||y>height+40)continue;const color={player:'#85d7df',enemy:'#ed8c83',neutral:'#b4b7a1'}[c.owner];if(c.id===selected){ctx.beginPath();ctx.arc(x,y,20,0,Math.PI*2);ctx.fillStyle='#dfb86c18';ctx.fill();ctx.strokeStyle='#e5be76';ctx.lineWidth=1.5;ctx.stroke()}ctx.fillStyle='#0c1a23';ctx.beginPath();ctx.arc(x,y,11,0,Math.PI*2);ctx.fill();ctx.strokeStyle=color;ctx.lineWidth=2;ctx.stroke();ctx.fillStyle=color;ctx.font='bold 13px system-ui';ctx.textAlign='center';ctx.fillText(c.capital?'★':'◆',x,y+4);ctx.font='14px system-ui';ctx.lineWidth=4;ctx.strokeStyle='#10252c';const label=c.nation+' · '+count(c);ctx.strokeText(label,x,y+33);ctx.fillText(label,x,y+33);ctx.fillStyle='#34505a';ctx.fillRect(x-15,y+16,30,3);ctx.fillStyle=color;ctx.fillRect(x-15,y+16,30*c.hp/c.maxHp,3);ctx.textAlign='left'}
}
let pointer=null;
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pointer={x:e.clientX,y:e.clientY,lon:cam.lon,lat:cam.lat,moved:false}});
canvas.addEventListener('pointermove',e=>{if(!pointer)return;const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;if(Math.hypot(dx,dy)>5)pointer.moved=true;if(pointer.moved){cam.lon=pointer.lon-dx/cam.scale;cam.lat=Math.max(-75,Math.min(80,pointer.lat+dy/cam.scale))}});
canvas.addEventListener('pointerup',e=>{if(pointer&&!pointer.moved&&state){const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;const nearest=state.cities.map(c=>({c,d:Math.hypot(project(c.lon,c.lat)[0]-x,project(c.lon,c.lat)[1]-y)})).sort((a,b)=>a.d-b.d)[0];if(nearest?.d<30)choose(nearest.c.id)}pointer=null});canvas.addEventListener('pointercancel',()=>pointer=null);
canvas.addEventListener('wheel',e=>{e.preventDefault();cam.scale=Math.max(1.5,Math.min(65,cam.scale*(e.deltaY<0?1.12:.89)))},{passive:false});
$('zoomIn').onclick=()=>cam.scale=Math.min(65,cam.scale*1.3);$('zoomOut').onclick=()=>cam.scale=Math.max(1.5,cam.scale/1.3);$('home').onclick=focusHome;$('view').onclick=()=>{cam={lon:10,lat:12,scale:Math.min(width/365,height/160)}};
function togglePause(){if(!state||state.over)return;paused=!paused;$('pause').textContent=paused?'▶ 繼續':'Ⅱ 暫停';notify(paused?'遊戲已暫停':'遊戲繼續')}
$('pause').onclick=togglePause;$('speed').onclick=()=>{speed=speed===1?2:speed===2?3:1;$('speed').textContent=speed+'×'};$('citySelect').onchange=e=>choose(e.target.value);$('scenario').onchange=factions;$('start').onclick=begin;$('newGame').onclick=()=>{sending=null;$('setup').showModal()};$('cancelSetup').onclick=()=>$('setup').close();$('help').onclick=()=>$('helpDialog').showModal();$('closeHelp').onclick=()=>$('helpDialog').close();$('again').onclick=()=>{$('result').close();$('setup').showModal()};$('setup').addEventListener('cancel',e=>{if(!state)e.preventDefault()});$('result').addEventListener('cancel',e=>e.preventDefault());
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!['SELECT','INPUT','BUTTON'].includes(e.target.tagName)&&!document.querySelector('dialog[open]')){e.preventDefault();togglePause()}if(e.key==='Escape')sending=null});
let uiTime=0;function frame(now){const dt=Math.min(.1,(now-last)/1000||0)*speed;last=now;if(state){tick(dt);uiTime+=dt;if(uiTime>.6){uiTime=0;const active=document.activeElement;if(!active||active.tagName!=='SELECT'){const ratio=$('ratio')?.value;const index=Array.from($('commands').querySelectorAll('button')).indexOf(active);render();if(ratio&&$('ratio'))$('ratio').value=ratio;if(index>=0)$('commands').querySelectorAll('button')[index]?.focus({preventScroll:true});}else{$('clock').textContent=formatTime(state.time);document.querySelectorAll('.resource b').forEach((b,i)=>{if(i<3)b.textContent=Math.floor(state.res[i])});}}}draw();requestAnimationFrame(frame)}
window.addEventListener('resize',resize);resize();factions();$('setup').showModal();requestAnimationFrame(frame);
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_campaign',description:'Read the current strategy campaign, city ownership and resources.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>state?{mode:state.mode,time:state.time,resources:state.res,cities:state.cities.map(c=>({id:c.id,owner:c.owner,units:c.units}))}:{started:false}})).catch(()=>{});}catch{}}
