// 君主對話資料（2026-09-21，Helen：「跨國之間有王與王的溝通時，跳出君主立繪與對話」）。
// resolve(game, owner) → {key, name, title, portrait, lines}：依「國籍→家族代碼→背景→時代」找君主；劇情戰役的主帥（players[].leader）優先。
// 歷史時代用真實君主（12 家族 × 4 時代＝48 位，由劇本工作流撰寫、審稿），現代／架空／科幻用虛構元首（不指名真實政治人物，Helen 2026-09-21 拍板）。
// 立繪：portraits/<portrait>.png（Codex 生圖，見 Codex美術發包_君主立繪.md）；沒有圖就顯示剪影＋姓氏。台詞是遊戲設計，不是史料。
(function(root){
'use strict';
const DATA=root.RULER_DATA||(typeof require==='function'?(()=>{try{return require('./ruler-data.js')}catch{return null}})():null)||{families:{},nations:{},generic:{},leaders:{}};
const KINDS=['intro','contact','war','warReply','peace','accept','reject','rebuff','betray','truceEnd','attacking','attacked','defeated','victory','allyAccept','allyReject','greetFriendly','greetCold','threatDefy','threatYield','tributePay','tributeRefuse','giftThanks','intel'];
// 你送出訊息時，自己的君主先說一句（依訊息種類；{t}＝對方）
const SENT={greet:['{n}向{t}致意，願兩國互通有無。','{n}遣使問候{t}，望彼此相安。'],threaten:['{n}最後警告{t}：識相的就退讓。','{t}若不收斂，{n}的大軍隨時可到。'],tribute:['{n}要求{t}獻上貢品，以示臣服。','{t}當知強弱之別，速備貢品送來。'],gift:['{n}備了薄禮送給{t}，聊表心意。','{n}以禮相贈，願{t}笑納。'],peace:['{n}願與{t}罷兵言和。','刀兵無益，{n}提議與{t}停戰。'],ally:['{n}願與{t}結為盟友，共進退。','{n}邀{t}結盟，同心禦敵。'],intel:['{n}想知道{t}如今與誰為敵、與誰為友。','{n}遣使打探{t}的近況與盟友。']};
const FALLBACK={greetFriendly:['{n}收到你的問候，甚為欣慰。願兩國長保和睦。','{n}在此回禮。遠方的朋友，願你的土地五穀豐登。'],greetCold:['{n}收到了。客套話就免了，各自安好吧。','問候收到。但{n}不會因此放下戒心。'],threatDefy:['威嚇？{n}的城牆不是嚇大的。有本事就來。','{n}從不接受恐嚇。你的使者可以回去了。'],threatYield:['{n}不願與你為敵……此事，容我再想想。','你的話，{n}記下了。我們無意冒犯貴國。'],tributePay:['{n}願送上 {gold} 黃金，換兩國安寧。','這 {gold} 黃金是{n}的心意，望你守諾。'],tributeRefuse:['貢品？{n}一分一毫都不會給你。','{n}不向任何人納貢。請你的使者原路返回。'],giftThanks:['{n}收下了你的厚禮，此情必記。','貴國的禮物，{n}甚是歡喜。願友誼長存。'],intel:['{n}此刻與{wars}交戰，與{peace}停戰。你問這做什麼？','據{n}所知：敵人是{wars}；停戰的有{peace}。'],intro:['{n}在此。此地的規矩，由本國來定。','{n}向你問候。願彼此各安其土。'],contact:['你的人踏進了{n}的疆界。','{n}的城池就在眼前，請自重。'],war:['{n}對你宣戰！','從今日起，{n}與你勢不兩立。'],warReply:['你選擇了戰爭，{n}奉陪到底。','既然如此，戰場上見。'],peace:['{n}願意停戰，你意下如何？','刀兵無益，{n}提議罷手。'],accept:['好，{n}答應你。','就依你所言，兩國罷兵。'],reject:['{n}不接受。','時機未到，{n}拒絕。'],rebuff:['你拒絕了{n}的善意，後果自負。','既然不領情，那就別再談了。'],betray:['{n}撕毀盟約，向你宣戰！','和平到此為止。'],truceEnd:['休戰結束，{n}不會再客氣。','時候到了，各憑本事。'],attacking:['{n}的大軍已經出發。','準備好，{n}來了。'],attacked:['你竟敢攻打{n}的都城！','{n}的城牆不會輕易倒下。'],defeated:['{n}……敗了。','記住今日，{n}不會被遺忘。'],victory:['勝利屬於{n}。','這片土地，如今歸{n}所有。'],allyAccept:['{n}願與你結盟。','從今起，你我共進退。'],allyReject:['{n}不與你結盟。','結盟之事，免談。']};
const hash=s=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0};
// 家族的本尊國：只有本尊才用家族君主（義大利借法國美術，但不能讓法國總統／查理曼替義大利說話——Helen 2026-09-21 回報）
const OWN={tw:'Taiwan',cn:'China',jp:'Japan',kr:'South Korea',mn:'Mongolia',in:'India',ru:'Russia',gb:'United Kingdom',fr:'France',de:'Germany',us:'United States of America',au:'Australia'};
// 借圖國家的現代元首稱謂（虛構人物，只用職稱）
const HEAD={'Taiwan Indigenous':'頭目','Vietnam':'主席','North Korea':'領導人','Thailand':'總理','Indonesia':'總統','Philippines':'總統','Malaysia':'首相','Cambodia':'首相','Pakistan':'總理','Sri Lanka':'總統','Nepal':'總理','Bhutan':'國王','Turkey':'總統','Iran':'總統','Iraq':'總理','Saudi Arabia':'國王','Egypt':'總統','Israel':'總理','Ethiopia':'總理','Nigeria':'總統','South Africa':'總統','Madagascar':'總統','Italy':'總理','Spain':'首相','Switzerland':'聯邦主席','Greece':'總理','Morocco':'國王','Tunisia':'總統','Netherlands':'首相','Sweden':'首相','Norway':'首相','Finland':'總統','Iceland':'總理','Poland':'總統','Ukraine':'總統','Canada':'總理','Mexico':'總統','Cuba':'主席','Peru':'總統','Bolivia':'總統','Brazil':'總統','Argentina':'總統','New Zealand':'總理','Papua New Guinea':'總理'};
// 已完成專屬立繪、但仍沿用通用外交台詞的國家。每完成一國就加入此表，避免畫完後仍顯示借用家族或通用立繪。
const PORTRAIT_CODE={'North Korea':'nk','Vietnam':'vn','Thailand':'th','Indonesia':'id','Philippines':'ph','Malaysia':'my','Cambodia':'kh','Pakistan':'pk','Sri Lanka':'lk','Nepal':'np','Bhutan':'bt','Turkey':'tr','Iran':'ir','Iraq':'iq','Saudi Arabia':'sa','Egypt':'eg','Israel':'il','Italy':'it','Spain':'es','Netherlands':'nl','Switzerland':'ch','Sweden':'se','Norway':'no','Finland':'fi','Iceland':'is','Poland':'pl','Ukraine':'ua','Greece':'gr','Canada':'ca','Mexico':'mx','Cuba':'cu','Peru':'pe','Bolivia':'bo','Argentina':'ar','Brazil':'br','Morocco':'ma','Tunisia':'tn','Ethiopia':'et','Nigeria':'ng','South Africa':'za','Madagascar':'mg','New Zealand':'nz','Papua New Guinea':'pg'};/* 43 個借圖國家的立繪代碼＝cultures.js 的國家代碼（2026-09-21 補齊；第二批立繪 <code>-historical-age<N>／<code>-modern） */
// 借圖國家的通用台詞：現代（中性外交辭令）；歷史時代用 FALLBACK（{n}＝該時代政權名＋君主）
const GENERIC_MODERN={greetFriendly:['{n}收到貴國問候，願兩國關係更進一步。','謝謝貴國的善意，{n}期待雙方合作。'],greetCold:['{n}收到了。外交上的客套，改變不了現況。','問候收到。{n}會持續觀察貴國的作為。'],threatDefy:['{n}不接受任何形式的威脅。','恐嚇對{n}沒有用，請回到談判桌。'],threatYield:['{n}希望避免衝突，願意重新評估雙方關係。','為了人民的安全，{n}暫時不與貴國對抗。'],tributePay:['{n}同意提供 {gold} 黃金的援助，換取和平。','這 {gold} 黃金是{n}的誠意，希望貴國信守承諾。'],tributeRefuse:['{n}不會向任何國家繳納貢品。','貴國的要求不合理，{n}拒絕。'],giftThanks:['{n}感謝貴國的援助，人民會記得這份情誼。','貴國的禮物已收到，{n}深表謝意。'],intel:['{n}目前與{wars}交戰，與{peace}維持停火。','據{n}掌握：交戰中的是{wars}，停火的是{peace}。'],intro:['{n}向各國致意，願以和平與貿易交往。','{n}在此。我們不求戰，但也不怕戰。'],contact:['貴國的部隊已進入{n}的視線範圍。','{n}注意到貴國的動向了。'],war:['談判破裂，{n}正式向貴國宣戰。','{n}別無選擇，今日對貴國宣戰。'],warReply:['貴國選擇了戰爭，{n}會奉陪。','{n}收到宣戰通知。我們會保衛家園。'],peace:['{n}提議停火，讓人民喘口氣。','戰爭沒有贏家，{n}願意停戰。'],accept:['{n}接受。願和平長久。','好，{n}同意這項協議。'],reject:['{n}無法接受目前的條件。','時機不對，{n}拒絕。'],rebuff:['貴國拒絕了{n}的提議，後果自負。','{n}的善意到此為止。'],betray:['情勢改變了，{n}撕毀停火協議。','{n}宣布停火結束，重新開戰。'],truceEnd:['休戰期結束，{n}已做好準備。','各國的緩衝期到此為止。'],attacking:['{n}的部隊已經出發。','{n}正式展開行動，請貴國自重。'],attacked:['{n}的首都遭到攻擊！我們會守到最後。','貴國攻擊{n}的政府所在地，這是全面戰爭。'],defeated:['{n}投降了。請善待我們的人民。','{n}的政府倒下了，歷史會記住這一天。'],victory:['{n}贏得了這場戰爭。願和平重新降臨。','戰爭結束，{n}勝利。'],allyAccept:['{n}同意結盟，共同進退。','好，{n}與貴國從此並肩。'],allyReject:['{n}目前不考慮結盟。','結盟的時機未到，{n}婉拒。']};
function groupOf(mode){return ['modern','fantasy','scifi'].includes(mode)?mode:'historical'}
function nationZh(game,owner){try{return game.nationLabel?game.nationLabel(owner).replace(/（.*$/,''):game.players[owner].nation}catch{return game.players[owner].nation}}
// 劇情主帥：players[].leader 對應 DATA.leaders，覆蓋在國籍／背景君主之上。
// 只蓋有寫的欄位；沒寫的（尤其是 24 種外交台詞）沿用原本的，所以一位主帥最少只要名字＋頭銜＋借用的立繪。
function resolve(game,owner){const p=game.players?.[owner];if(!p)return null;const base=resolveBase(game,owner);const key=p.leader||(game.scenario?.id?game.scenario.id+"#"+owner:null);/* 劇情戰役的勢力預設用「劇情代號#勢力序號」對應主帥，不必在 campaigns.js 逐一標 leader */const L=key&&DATA.leaders?.[key];if(!L)return base;return {key:"leader:"+key,name:L.name||base?.name,title:L.title!=null?L.title:(base?.title||""),portrait:L.portrait||base?.portrait,era:L.era!=null?L.era:base?.era,lines:Object.assign({},base?.lines,L.lines||{})}}
function resolveBase(game,owner){const p=game.players?.[owner];if(!p)return null;const group=groupOf(game.mode),age=game.ages?.[owner]||0,code=game.artCode?.(owner)||null;
 
 if(group==='historical'){const V=DATA.variants?.[game.mode]?.[p.nation]?.[age];/* 背景專屬君主（2026-09-22 Helen：「選西方史實、選東方角色，人物會對應到該時期嗎？」→ 42 格依西方／東方分期各補一位） */if(V)return {key:'variant:'+game.mode+':'+p.nation+':'+age,name:V.name,title:V.title||'',portrait:V.portrait||((DATA.nationCodes?.[p.nation]||code||'xx')+'-'+game.mode+'-age'+age),lines:V.lines,era:V.era};const byNation=DATA.nations?.[p.nation]?.[age];if(byNation)return {key:p.nation+':'+age,name:byNation.name,title:byNation.title||'',portrait:byNation.portrait||((DATA.nationCodes?.[p.nation]||code||'xx')+'-historical-age'+age),lines:byNation.lines,era:byNation.era};
  const fam=code&&OWN[code]===p.nation&&DATA.families?.[code]?.[age];if(fam)return {key:code+':'+age,name:fam.name,title:fam.title||'',portrait:fam.portrait||(code+'-historical-age'+age),lines:fam.lines,era:fam.era};
  const polity=(game.playerName?game.playerName(owner):p.nation).replace('（你）',''),portraitCode=PORTRAIT_CODE[p.nation];return {key:'generic:'+owner,name:polity+'君主',title:'',portrait:portraitCode?(portraitCode+'-historical-age'+age):'generic-historical',lines:FALLBACK,generic:true}}
 const own=code&&OWN[code]===p.nation;const nz=nationZh(game,owner);
 if(group==='modern'&&!own){const M=DATA.nationsModern?.[p.nation];/* 借圖國家的現代元首專屬台詞（2026-09-21 借圖 43 國工作流） */if(M)return {key:'modern-nation:'+p.nation,name:M.name,title:M.title||'政府',portrait:M.portrait||((PORTRAIT_CODE[p.nation]||'xx')+'-modern'),lines:M.lines};const title=HEAD[p.nation]||'元首',portraitCode=PORTRAIT_CODE[p.nation];return {key:'modern-generic:'+p.nation,name:nz+title,title:'政府',portrait:portraitCode?(portraitCode+'-modern'):'generic-modern',lines:GENERIC_MODERN,generic:true}}
 const gen=DATA.generic?.[group+'-'+code]||DATA.generic?.[group];
 if(gen)return {key:group+':'+(code||owner),name:group==='modern'?gen.name:nz+gen.name,title:gen.title||'',portrait:gen.portrait||(group==='modern'?code+'-modern':group),lines:gen.lines,generic:true};
 return {key:'generic:'+owner,name:nz+'元首',title:'',portrait:'generic-'+group,lines:FALLBACK,generic:true}}
function fill(s,who,vars){const v=Object.assign({n:who?.name||'',wars:'（無）',peace:'（無）',gold:'',total:'',t:''},vars||{});for(const k of ['wars','peace'])if(Array.isArray(v[k]))v[k]=v[k].length?v[k].join('、'):'（無）';return s.replace(/\{(\w+)\}/g,(m,k)=>v[k]!=null?String(v[k]):m)}
function line(who,kind,seed=0,vars){const set=(who?.lines?.[kind]&&who.lines[kind].length?who.lines[kind]:FALLBACK[kind])||[];if(!set.length)return '';return fill(set[hash(String(seed)+kind)%set.length],who,vars)}
function sentLine(who,kind,seed=0,vars){const set=SENT[kind]||[];if(!set.length)return '';return fill(set[hash(String(seed)+kind)%set.length],who,vars)}
root.RULERS={resolve,line,sentLine,KINDS,data:DATA};
if(typeof module!=='undefined'&&module.exports)module.exports=root.RULERS;
})(typeof window!=='undefined'?window:globalThis);
